name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install traceroute
      run: sudo apt-get install traceroute curl
    
    - name: curl
      run: curl neo4j.com

    - name: Traceroute
      run: traceroute neo4j.com

    - name: Ping
      run: ping neo4j.com -c 5

    - name: Test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: wordPressUpload -Pwordpress-host="neo4j.com" -Pwordpress-username="${WORDPRESS_USER}" -Pwordpress-password="${WORDPRESS_PASSWORD}" -Pstage=production --stacktrace
      env:
        WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
        WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
